---
title: "Project1 Codebook"
author: "Yingxi Kong"
date: '2024-10-01'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(visdat)
library(gtsummary)
library(kableExtra)
library(ggpubr)
library(gt)
library(car)
library(lme4)
library(lmerTest)
library(corrplot)

data <- read.csv("project1.csv")
course_record <- read.csv("course_record.csv")
aqi_values <- read.csv("aqi_values.csv")
marathon_dates <-  read.csv("marathon_dates.csv")

colnames(data) <- c("race", "year", "sex", "flag", "age", "CR_pct", "Tdc", "Twc", "rh", "Tgc", "SRWm2", "DP", "Wind", "WBGT")

data$flag <- case_when(data$flag == "" ~ NA, TRUE ~ data$flag)
data$flag <- as.factor(data$flag)

course_record$Race <- case_when(course_record$Race == "B" ~ 0,
                                course_record$Race == "C" ~ 1,
                                course_record$Race == "NY" ~ 2,
                                course_record$Race == "TC" ~ 3,
                                course_record$Race == "D" ~ 4,
                                TRUE ~ NA)
course_record$Gender <- case_when(course_record$Gender == "M" ~ 1,
                                  course_record$Gender == "F" ~ 0,
                                  TRUE ~ NA)

data <- data %>%
  left_join(course_record, join_by("sex" == "Gender", "race" == "Race", "year" == "Year"))

data$sex <- as.factor(data$sex)
data$race <- case_when(data$race == 0 ~ "Boston",
                       data$race == 1 ~ "Chicago",
                       data$race == 2 ~ "NYC",
                       data$race == 3 ~ "Twin Cities",
                       data$race == 4 ~ "Grandmas")

data <- data %>% left_join(marathon_dates, by = c("race" = "marathon", "year" = "year"))

aqi_values_sum <- aqi_values %>% 
  group_by(marathon, date_local) %>%
  summarize(ave_arithmetic_mean = mean(arithmetic_mean, na.rm = TRUE), .groups = "drop")

data <- data %>%
  mutate(date = as.Date(date)) 
aqi_values_sum <- aqi_values_sum %>%
  mutate(date_local = as.Date(date_local))

# Joining with the main dataset
data <- data %>%
  left_join(aqi_values_sum, by = c("race" = "marathon", "date" = "date_local"))

colnames(data)[17] <- "aqi"

```


```{r, out.width= "80%"}
# Missing Pattern
# vis_dat(data)

# Classify each observation to age groups by gender's quantile value
# data <- data %>%
#   group_by(sex, .groups = "drop") %>%
#   mutate(age_group = cut(age, breaks = quantile(age, probs = seq(0, 1, 0.25), na.rm = TRUE),
#                                   include.lowest = TRUE, 
#                                   labels = c("Lower Age", "Lower-Mid Age", 
#                                              "Upper-Mid Age", "Highest Age")))


data <- data %>%
  group_by(sex) %>%
  mutate(age_group = cut(age, 
                         breaks = c(0, 21, 31, 47, 62, Inf), 
                         include.lowest = TRUE, 
                         labels = c("Younger", "Lower Age", "Lower-Mid Age", 
                                    "Upper-Mid Age", "Highest Age"))) %>%
  ungroup()

# Summary Table by Age group and Sex
summary_table <- data %>%
  group_by(age_group, sex) %>%
  summarize(N = n(),
            min_performance = round(min(CR_pct, na.rm = TRUE), 3),
            mean_performance = round(mean(CR_pct, na.rm = TRUE), 3),
            median_performance = round(median(CR_pct, na.rm = TRUE), 3),
            max_performance = round(max(CR_pct, na.rm = TRUE), 3))
summary_table$sex <- ifelse(summary_table$sex == 1, "Male", "Female")

knitr::kable(summary_table, 
             col.names = c("Age Group", "Sex", "N", "Min Performance",
                           "Mean Performance", "Median Performance", "Max Performance"),
             caption = "Summary of Marathon Performance by Age Group and Sex") %>%
  kable_styling(latex_options = "HOLD_position",
                font_size = 8)

```

```{r, out.width= "80%"}
# male summary
male_summary <- data %>%
  filter(sex == 1) %>%
  group_by(age) %>%
  summarise(mean_CR = mean(CR_pct, na.rm = TRUE),
            se_CR = sd(CR_pct, na.rm = TRUE))

# create the plot
ageplot_male <- ggplot(male_summary, aes(x = age, y = mean_CR)) +
  geom_point(color = "grey", size = 1) +          
  geom_errorbar(aes(ymin = mean_CR - se_CR, ymax = mean_CR + se_CR), width = 1, color = "grey") +  
  geom_smooth(se = FALSE, color = "black", size = 1, method = "loess", linetype = 2) +
  labs(title = "Men", x = "Age (yrs)", y = "Best Time (%CR)") + 
  ylim(0, 400) +
  theme_minimal(base_size = 15) +               
  theme(plot.title = element_text(hjust = 0.5))

# women summary
women_summary <- data %>%
  filter(sex == 0) %>%
  group_by(age) %>%
  summarise(mean_CR = mean(CR_pct, na.rm = TRUE),
            se_CR = sd(CR_pct, na.rm = TRUE))

# create the plot
ageplot_female <- ggplot(women_summary, aes(x = age, y = mean_CR)) +
  geom_point(color = "grey", size = 1) + 
  geom_errorbar(aes(ymin = mean_CR - se_CR, ymax = mean_CR + se_CR), width = 1, color = "grey") + 
  geom_smooth(se = FALSE, color = "black", size = 1, method = "loess", linetype = 2) + 
  labs(title = "Women", x = "Age (yrs)", y = "Best Time (%CR)") + 
  ylim(0, 400) +              
  theme_minimal(base_size = 15) + 
  theme(plot.title = element_text(hjust = 0.5))

# merge the two plots together
ggarrange(ageplot_male, ageplot_female)
```

```{r, out.width= "80%"}
data$flag <- factor(data$flag, levels = c("White", "Green", "Yellow", "Red", "Black", NA))
data$sex <- ifelse(data$sex == 0, "Female", "Male")
ggplot(data, aes(x = sex, y = CR_pct, fill = flag)) +
  geom_boxplot() +
  ggtitle("Marathon Performance by WBGT Categories and Sex") +
  theme_minimal() +
  labs(x = "Sex", y = "Marathon Performance (CR_pct)", fill = "Risk of Heat Illness") +
  theme(legend.position = "bottom")
```
\newpage

```{r}
tbl_summary <- data %>%
  select(-c("year", "CR", "age_group", "date")) %>%
  mutate(
    race = case_when(race == "Boston" ~ "Boston Marathon",
                     race == "Chicago" ~ "Chicago Marathon",
                     race == "NYC" ~ "New York City Marathon",
                     race == "Twin Cities" ~ "Twin Cities Marathon",
                     race == "Grandmas" ~ "Grandma’s Marathon",
                     TRUE ~ "Missing"),
    flag = case_when(flag == 'White' ~ "WBGT < 10C",
                     flag == 'Green' ~ "WBGT 10-18C",
                     flag == 'Yellow' ~ "WBGT > 18-23C",
                     flag == 'Red' ~ "WBGT > 23-28C",
                     TRUE ~ "Missing")) %>%
  tbl_summary(by = race,
              label = list(age ~ "Age",
                           sex ~ "Gender",
                           CR_pct ~ "Percent off current course record ",
                           Tdc ~ "Dry bulb temperature",
                           Twc ~ "Wet bulb temperature",
                           rh ~ "Percent relative humidity",
                           Tgc ~ "Black globe temperature",
                           SRWm2 ~ "Solar radiation in Watts",
                           DP ~ "Dew Point",
                           aqi ~ "Air Quality Index"),
              statistic = all_continuous() ~ "{mean} ({sd})",
              missing = "ifany",
              missing_text = "Missing") %>%
  modify_spanning_header(update =  all_stat_cols() ~  "**Race**") %>%
  modify_footnote(update = all_stat_cols() ~ "Mean (SD) for continuous; n (%) for categorical") %>%
  bold_labels()

tbl_summary %>%
  as_gt() %>%
  cols_align(align = "center", columns = everything()) %>%
  tab_options(
    table.width = pct(100),
    table.align = "center"
  ) %>%
  cols_width(
    everything() ~ px(75)
  ) %>%
  tab_header(
    title = md("Table 1: Summary Statistics by Race")
  ) %>%
  tab_style(
    style = cell_text(size = px(8)), 
    locations = cells_title(groups = "title")
  ) %>%
  tab_style(
    style = cell_text(size = px(7)), 
    locations = cells_body()
  ) %>%
  tab_style(
    style = cell_text(size = px(7)),
    locations = cells_column_labels()
  )
```



```{r}
# tbl_summary_female <- data %>%
#   filter(sex == "Female") %>%
#   select(-c(year, sex, CR, age_group, date)) %>%
#   mutate(
#     race = case_when(race == "Boston" ~ "Boston Marathon",
#                      race == "Chicago" ~ "Chicago Marathon",
#                      race == "NYC" ~ "New York City Marathon",
#                      race == "Twin Cities" ~ "Twin Cities Marathon",
#                      race == "Grandmas" ~ "Grandma’s Marathon",
#                      TRUE ~ "Missing"),
#     flag = case_when(flag == 'White' ~ "WBGT < 10C",
#                      flag == 'Green' ~ "WBGT 10-18C",
#                      flag == 'Yellow' ~ "WBGT > 18-23C",
#                      flag == 'Red' ~ "WBGT > 23-28C",
#                      TRUE ~ "Missing")) %>%
#   tbl_summary(by = race,
#               label = list(age ~ "Age",
#                            CR_pct ~ "Percent off current course record ",
#                            Tdc ~ "Dry bulb temperature",
#                            Twc ~ "Wet bulb temperature",
#                            rh ~ "Percent relative humidity",
#                            Tgc ~ "Black globe temperature",
#                            SRWm2 ~ "Solar radiation in Watts",
#                            DP ~ "Dew Point"),
#               statistic = all_continuous() ~ "{mean} ({sd})",
#               missing = "ifany",
#               missing_text = "Missing") %>%
#   modify_spanning_header(update =  all_stat_cols() ~  "**Race**") %>%
#   modify_footnote(update = all_stat_cols() ~ "Mean (SD) for continuous; n (%) for categorical") %>%
#   bold_labels()
# 
# tbl_summary_female %>%
#   as_gt() %>%
#   cols_align(align = "center", columns = everything()) %>%
#   tab_options(
#     table.width = pct(100),
#     table.align = "center"
#   ) %>%
#   cols_width(
#     everything() ~ px(75)
#   ) %>%
#   tab_header(
#     title = md("Table 1: Summary Statistics by Race")
#   ) %>%
#   tab_style(
#     style = cell_text(size = px(8)), 
#     locations = cells_title(groups = "title")
#   ) %>%
#   tab_style(
#     style = cell_text(size = px(7)), 
#     locations = cells_body()
#   ) %>%
#   tab_style(
#     style = cell_text(size = px(7)),
#     locations = cells_column_labels()
#   )
```


```{r}
# tbl_summary_male <- data %>%
#   filter(sex == "Male") %>%
#   select(-c(year, sex, CR, age_group, date)) %>%
#   mutate(
#     race = case_when(race == "Boston" ~ "Boston Marathon",
#                      race == "Chicago" ~ "Chicago Marathon",
#                      race == "NYC" ~ "New York City Marathon",
#                      race == "Twin Cities" ~ "Twin Cities Marathon",
#                      race == "Grandmas" ~ "Grandma’s Marathon",
#                      TRUE ~ "Missing"),
#     flag = case_when(flag == 'White' ~ "WBGT < 10C",
#                      flag == 'Green' ~ "WBGT 10-18C",
#                      flag == 'Yellow' ~ "WBGT > 18-23C",
#                      flag == 'Red' ~ "WBGT > 23-28C",
#                      TRUE ~ "Missing")) %>%
#   tbl_summary(by = race,
#               label = list(age ~ "Age",
#                            CR_pct ~ "Percent off current course record ",
#                            Tdc ~ "Dry bulb temperature",
#                            Twc ~ "Wet bulb temperature",
#                            rh ~ "Percent relative humidity",
#                            Tgc ~ "Black globe temperature",
#                            SRWm2 ~ "Solar radiation in Watts",
#                            DP ~ "Dew Point"),
#               statistic = all_continuous() ~ "{mean} ({sd})",
#               missing = "ifany",
#               missing_text = "Missing") %>%
#   modify_spanning_header(update =  all_stat_cols() ~  "**Race**") %>%
#   modify_footnote(update = all_stat_cols() ~ "Mean (SD) for continuous; n (%) for categorical") %>%
#   bold_labels()
# 
# tbl_summary_male %>%
#   as_gt() %>%
#   cols_align(align = "center", columns = everything()) %>%
#   tab_options(
#     table.width = pct(100),
#     table.align = "center"
#   ) %>%
#   cols_width(
#     everything() ~ px(75)
#   ) %>%
#   tab_header(
#     title = md("Table 1: Summary Statistics by Race")
#   ) %>%
#   tab_style(
#     style = cell_text(size = px(8)), 
#     locations = cells_title(groups = "title")
#   ) %>%
#   tab_style(
#     style = cell_text(size = px(7)), 
#     locations = cells_body()
#   ) %>%
#   tab_style(
#     style = cell_text(size = px(7)),
#     locations = cells_column_labels()
#   )

```

```{r}
# Correlation Plot 
cor_matrix <- cor(data[,-c(1, 2, 3, 4, 5, 15, 16, 18)], use = "complete.obs")

corrplot(cor_matrix, method = "color", type = "lower", 
         tl.col = "black", tl.cex = 0.8, addCoef.col = "black",
         number.cex = 0.7, col = colorRampPalette(c("steelblue", "white", "steelblue"))(200))
```


```{r}
fig_Tdc <- ggplot(data, aes(x = Tdc, y = CR_pct, color = age_group, linetype = sex)) +
  geom_smooth(method = "loess", se = FALSE, size = 0.5) +
  labs(title = "Tdc", x = "Temperature (Tdc)", y = "Percent Off Course Record",
       color = "Age Group", linetype = "Gender") +
  theme_minimal() +
  theme(axis.text = element_text(size = 8),
        axis.title = element_text(size = 8),
        plot.title = element_text(size = 10, face = "plain"),
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7),
        legend.key.width = unit(0.5, "cm"),
        legend.spacing.x = unit(0.2, "cm")) + 
  guides(color = guide_legend(nrow = 1),
         linetype = guide_legend(nrow = 1))

# Repeat the same for Twc, Tgc, and DP plots
fig_Twc <- ggplot(data, aes(x = Twc, y = CR_pct, color = age_group, linetype = sex)) +
  geom_smooth(method = "loess", se = FALSE, size = 0.5) +
  labs(title = "Twc", x = "Temperature (Twc)", y = "Percent Off Course Record",
       color = "Age Group", linetype = "Gender") + 
  theme_minimal() +
  theme(axis.text = element_text(size = 8),
        axis.title = element_text(size = 8),
        plot.title = element_text(size = 10, face = "plain"),
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7),
        legend.key.width = unit(0.5, "cm"),  
        legend.spacing.x = unit(0.2, "cm")) + 
  guides(color = guide_legend(nrow = 1), 
         linetype = guide_legend(nrow = 1))

fig_Tgc <- ggplot(data, aes(x = Tgc, y = CR_pct, color = age_group, linetype = sex)) +
  geom_smooth(method = "loess", se = FALSE, size = 0.5) +
  labs(title = "Tgc", x = "Temperature (Tgc)", y = "Percent Off Course Record",
       color = "Age Group", linetype = "Gender") + 
  theme_minimal() +
  theme(axis.text = element_text(size = 8),
        axis.title = element_text(size = 8),
        plot.title = element_text(size = 10, face = "plain"),
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7),
        legend.key.width = unit(0.5, "cm"),  
        legend.spacing.x = unit(0.2, "cm")) + 
  guides(color = guide_legend(nrow = 1), 
         linetype = guide_legend(nrow = 1))

fig_DP <- ggplot(data, aes(x = DP, y = CR_pct, color = age_group, linetype = sex)) +
  geom_smooth(method = "loess", se = FALSE, size = 0.5) +
  labs(title = "DP", x = "Dew Point (DP)", y = "Percent Off Course Record",
       color = "Age Group", linetype = "Gender") + 
  theme_minimal() +
  theme(axis.text = element_text(size = 8),
        axis.title = element_text(size = 8),
        plot.title = element_text(size = 10, face = "plain"),
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7),
        legend.key.width = unit(0.5, "cm"),  
        legend.spacing.x = unit(0.2, "cm")) + 
  guides(color = guide_legend(nrow = 1), 
         linetype = guide_legend(nrow = 1))

# Arrange the plots with a more compact legend
temp_figs <- ggarrange(fig_Tdc, fig_Twc, fig_Tgc, fig_DP, 
                       ncol = 2, nrow = 2,
                       common.legend = TRUE, legend = "bottom")

annotate_figure(temp_figs, top = text_grob("Overall Performance vs. Temperature Conditions", 
                                           face = "bold", size = 12))

```
```{r}
fig_WBGT <- ggplot(data, aes(x = WBGT, y = CR_pct, color = age_group, linetype = sex)) +
  geom_smooth(method = "loess", se = FALSE, size = 0.5) +
  facet_wrap(~race, scales = "free") + 
  labs(title = "WBGT",
       x = "WBGT", y = "Percent Off Course Record") + 
  theme_minimal() +
  theme(axis.text = element_text(size = 8),
        axis.title=element_text(size = 8),
        legend.text=element_text(size = 6),
        legend.title=element_text(size = 7),
        plot.title = element_text(size = 10),
        legend.position = "bottom") +
  guides(color = guide_legend(nrow = 1), linetype = guide_legend(nrow = 1))

fig_SRWm2 <- ggplot(data, aes(x = SRWm2, y = CR_pct, color = age_group, linetype = sex)) +
  geom_smooth(method = "loess", se = FALSE, size = 0.5) +
  facet_wrap(~race, scales = "free") + 
  labs(title = "SRWm2",
       x = "Solar Radiation (SRWm2)", y = "Percent Off Course Record") + 
  theme_minimal() +
  theme(axis.text = element_text(size = 8),
        axis.title=element_text(size = 8),
        legend.text=element_text(size = 6),
        legend.title=element_text(size = 7),
        plot.title = element_text(size = 10),
        legend.position = "bottom") +
  guides(color = guide_legend(nrow = 1), linetype = guide_legend(nrow = 1))

fig_rh <- ggplot(data, aes(x = rh, y = CR_pct, color = age_group, linetype = sex)) +
  geom_smooth(method = "loess", se = FALSE, size = 0.5) +
  facet_wrap(~race, scales = "free") + 
  labs(title = "rh",
       x = "Humidity (rh)", y = "Percent Off Course Record") + 
  theme_minimal() +
  theme(axis.text = element_text(size = 8),
        axis.title=element_text(size = 8),
        legend.text=element_text(size = 6),
        legend.title=element_text(size = 7),
        plot.title = element_text(size = 10),
        legend.position = "bottom") +
  guides(color = guide_legend(nrow = 1), linetype = guide_legend(nrow = 1))

fig_wind <- ggplot(data, aes(x = Wind, y = CR_pct, color = age_group, linetype = sex)) +
  geom_smooth(method = "loess", se = FALSE, size = 0.5) +
  facet_wrap(~race, scales = "free") + 
  labs(title = "Wind",
       x = "Wind", y = "Percent Off Course Record") + 
  theme_minimal() +
  theme(axis.text = element_text(size = 8),
        axis.title=element_text(size = 8),
        legend.text=element_text(size = 6),
        legend.title=element_text(size = 7),
        plot.title = element_text(size = 10),
        legend.position = "bottom") +
  guides(color = guide_legend(nrow = 1), linetype = guide_legend(nrow = 1))

fig_aqi <- ggplot(data, aes(x = aqi, y = CR_pct, color = age_group, linetype = sex)) +
  geom_smooth(method = "loess", se = FALSE, size = 0.5) +
  facet_wrap(~race, scales = "free") + 
  labs(title = "aqi",
       x = "Air Quality Index (aqi)", y = "Percent Off Course Record") + 
  theme_minimal() +
  theme(axis.text = element_text(size = 8),
        axis.title=element_text(size = 8),
        legend.text=element_text(size = 6),
        legend.title=element_text(size = 7),
        plot.title = element_text(size = 10),
        legend.position = "bottom") +
  guides(color = guide_legend(nrow = 1), linetype = guide_legend(nrow = 1))

fig_WBGT
fig_SRWm2
fig_rh
fig_wind
fig_aqi
```


```{r}
female_Tdc <- data %>%
  filter(sex == "Female") %>%
  group_by(age_group, Tdc) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE))

female_Tdc_fig <- ggplot(female_Tdc, aes(x = Tdc, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Female") + 
  theme_minimal()

male_Tdc <- data %>%
  filter(sex == "Male") %>%
  group_by(age_group, Tdc) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE))

male_Tdc_fig <- ggplot(male_Tdc, aes(x = Tdc, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Male") +
  theme_minimal()

ggarrange(female_Tdc_fig, male_Tdc_fig, common.legend = TRUE)
```


```{r}
female_Twc <- data %>%
  filter(sex == "Female") %>%
  group_by(age_group, Twc) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE))

female_Twc_fig <- ggplot(female_Twc, aes(x = Twc, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Female") + 
  theme_minimal()

male_Twc <- data %>%
  filter(sex == "Male") %>%
  group_by(age_group, Twc) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE))

male_Twc_fig <- ggplot(male_Twc, aes(x = Twc, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Male") +
  theme_minimal()

ggarrange(female_Twc_fig, male_Twc_fig, common.legend = TRUE)
```

```{r}
female_Tgc <- data %>%
  filter(sex == "Female") %>%
  group_by(age_group, Tgc) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE)) %>%
  ungroup()

female_Tgc_fig <- ggplot(female_Tgc, aes(x = Tgc, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Female") + 
  theme_minimal()

male_Tgc <- data %>%
  filter(sex == "Male") %>%
  group_by(age_group, Tgc) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE)) %>%
  ungroup()

male_Tgc_fig <- ggplot(male_Tgc, aes(x = Tgc, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Male") +
  theme_minimal()

ggarrange(female_Tgc_fig, male_Tgc_fig, common.legend = TRUE)
```

```{r}
low_humidity_df <- data %>%
  filter(rh < 5)

high_humidity_df <- data %>%
  filter(rh > 5)

female_low_rh <- low_humidity_df %>%
  filter(sex == "Female") %>%
  group_by(age_group, rh) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE)) %>%
  ungroup()

female_low_rh_fig <- ggplot(female_low_rh, aes(x = rh, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Female (Low Humidity)") + 
  theme_minimal()

male_low_rh <- low_humidity_df %>%
  filter(sex == "Male") %>%
  group_by(age_group, rh) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE)) %>%
  ungroup()

male_low_rh_fig <- ggplot(male_low_rh, aes(x = rh, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Male (Low Humidity)") +
  theme_minimal()

female_high_rh <- high_humidity_df %>%
  filter(sex == "Female") %>%
  group_by(age_group, rh) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE)) %>%
  ungroup()

female_high_rh_fig <- ggplot(female_high_rh, aes(x = rh, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Female (High Humidity)") + 
  theme_minimal()

male_high_rh <- high_humidity_df %>%
  filter(sex == "Male") %>%
  group_by(age_group, rh) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE)) %>%
  ungroup()

male_high_rh_fig <- ggplot(male_high_rh, aes(x = rh, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Male (High Humidity)") +
  theme_minimal()

ggarrange(female_low_rh_fig, male_low_rh_fig, female_high_rh_fig, male_high_rh_fig, common.legend = TRUE)
```

```{r}
female_SRWm2 <- data %>%
  filter(sex == "Female") %>%
  group_by(age_group, SRWm2) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE)) %>%
  ungroup()

female_SRWm2_fig <- ggplot(female_SRWm2, aes(x = SRWm2, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "loess", se = FALSE, size = 0.8) + 
  ggtitle("Female") + 
  theme_minimal()

male_SRWm2 <- data %>%
  filter(sex == "Male") %>%
  group_by(age_group, SRWm2) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE)) %>%
  ungroup()

male_SRWm2_fig <- ggplot(male_SRWm2, aes(x = SRWm2, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "loess", se = FALSE, size = 0.8) + 
  ggtitle("Male") +
  theme_minimal()

ggarrange(female_SRWm2_fig, male_SRWm2_fig, common.legend = TRUE)
```
```{r}
female_DP <- data %>%
  filter(sex == "Female") %>%
  group_by(age_group, DP) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE)) %>%
  ungroup()

female_DP_fig <- ggplot(female_DP, aes(x = DP, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "loess", se = FALSE, size = 0.8) + 
  ggtitle("Female") + 
  theme_minimal()

male_DP <- data %>%
  filter(sex == "Male") %>%
  group_by(age_group, DP) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE)) %>%
  ungroup()

male_DP_fig <- ggplot(male_DP, aes(x = DP, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "loess", se = FALSE, size = 0.8) + 
  ggtitle("Male") +
  theme_minimal()

ggarrange(female_DP_fig, male_DP_fig, common.legend = TRUE)
```
```{r}
female_aqi <- data %>%
  filter(sex == "Female") %>%
  group_by(age_group, aqi) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE)) %>%
  ungroup()

female_aqi_fig <- ggplot(female_aqi, aes(x = aqi, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Female") + 
  theme_minimal()

male_aqi <- data %>%
  filter(sex == "Male") %>%
  group_by(age_group, aqi) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE)) %>%
  ungroup()

male_aqi_fig <- ggplot(male_aqi, aes(x = aqi, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Male") +
  theme_minimal()

ggarrange(female_aqi_fig, male_aqi_fig, common.legend = TRUE)
```

```{r}
female_WBGT <- data %>%
  filter(sex == "Female") %>%
  group_by(age_group, WBGT) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE)) %>%
  ungroup()

female_WBGT_fig <- ggplot(female_WBGT, aes(x = WBGT, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Female") + 
  theme_minimal()

male_WBGT <- data %>%
  filter(sex == "Male") %>%
  group_by(age_group, WBGT) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE)) %>%
  ungroup()

male_WBGT_fig <- ggplot(male_WBGT, aes(x = WBGT, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Male") +
  theme_minimal()

ggarrange(female_WBGT_fig, male_WBGT_fig, common.legend = TRUE)
```

```{r}
ggplot(data, aes(x = rh)) +
  geom_histogram(binwidth = 5, fill = "steelblue", color = "black") +
  ggtitle("Distribution of Humidity Values") +
  theme_minimal() +
  labs(x = "Relative Humidity (%)", y = "Frequency")

low_humidity_df <- data %>%
  filter(rh < 5)

high_humidity_df <- data %>%
  filter(rh > 5)

```

```{r}
by(data$age, data$sex, summary)
```

```{r}
female_wind <- data %>%
  filter(sex == "Female") %>%
  group_by(age_group, Wind) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE))

female_wind_fig <- ggplot(female_wind, aes(x = Wind, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Female") + 
  theme_minimal()

male_wind <- data %>%
  filter(sex == "Male") %>%
  group_by(age_group, Wind) %>%
  mutate(mean_CR_pct = mean(CR_pct, na.rm = TRUE))

male_wind_fig <- ggplot(male_wind, aes(x = Wind, y = mean_CR_pct, color = age_group)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, size = 0.8) + 
  ggtitle("Male") +
  theme_minimal()

ggarrange(female_wind_fig, male_wind_fig, common.legend = TRUE)
```

```{r}
# Fit the linear model with interactions
model_Tdc <- lm(CR_pct ~ Tdc*age + Tdc*sex, data = data)
summary(model_Tdc)

model_Twc <- lm(CR_pct ~ Tdc*age + Tdc*sex + Twc*age + Twc*sex, data = data)
summary(model_Twc)


model1 <- lmerTest::lmer(CR_pct ~ sex + rh + age + SRWm2 + Wind + WBGT + (1 | age), data = data)
summary(model1)
```
# Appendix

```{r ref.label = knitr::all_labels()}
#| echo: true
#| eval: false
```