---
title: "Project 3"
author: Yingxi Kong
output:
  pdf_document
---

# Abstract








# Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(lmerTest)
library(ggplot2)
library(kableExtra)
```


# Methods

```{r}
source("C:/Users/yingx/OneDrive/Desktop/Fall 2024/PHP 2550/Practical-Data-Analysis-Portfolio/Project3/R/Data Simulation.R", local = knitr::knit_global())
source("C:/Users/yingx/OneDrive/Desktop/Fall 2024/PHP 2550/Practical-Data-Analysis-Portfolio/Project3/R/Experiment.R", local = knitr::knit_global())
```

## Normal Distributed Y

## Vary G, R, c1/c2
```{r}
alpha <- 0
beta <- 1.5
gamma_sq <- 1
sigma_sq <- 1
B <- 10000
niter <- 100
c1 <- 20
c1c2_ratio_list <- c(2, 5, 10, 20)
G_list = c(5, 10, 15, 20, 25, 30)
data_folder_normal <- "C:/Users/yingx/OneDrive/Desktop/Fall 2024/PHP 2550/Practical-Data-Analysis-Portfolio/Project3/Data_normal/"
results_folder_normal <- "C:/Users/yingx/OneDrive/Desktop/Fall 2024/PHP 2550/Practical-Data-Analysis-Portfolio/Project3/Results_normal/"

# Finding optimal design 
set.seed(2550)
summary_metrics_df <- data.frame()
for (G in G_list) {
  for (ratio in c1c2_ratio_list) {
    result_df <- simulate_data_normal(G, alpha, beta, gamma_sq, sigma_sq, c1, ratio, B, niter,
                                      folder = data_folder_normal, 
                                      filename = paste0("Normal", "_", G, "_", ratio, "_", alpha, 
                                                        "_", beta, "_", gamma_sq, "_", sigma_sq,
                                                        "_data.csv"))
    c2 <- c1 / ratio
    cost_per_cluster <- B/G
    n_c2 <- floor((cost_per_cluster - c1)/c2)
    R <- n_c2 + 1
    data_path <- paste0(data_folder_normal, "Normal", "_", G, "_", ratio, "_", 
                        alpha, "_", beta, "_", gamma_sq, "_", sigma_sq, "_data.csv")
    summary_metrics <- normal_model(data_path, beta, niter, results_folder = results_folder_normal,
                                    filename = paste0("Results_normal", "_", G, "_", ratio, "_",
                                                      alpha, "_", beta, "_", gamma_sq, "_", sigma_sq, ".csv"))
    summary_metrics_df <- rbind(summary_metrics_df, summary_metrics)
  }
}
```

```{r}
varyGR_summary <- summary_metrics_df %>%
  dplyr::select(G, R, c1c2_ratio, beta_estimate, beta_variance, beta_bias, mse, coverage)

varyGR_summary %>%
  filter(c1c2_ratio == 10) %>%
  kable(col.names = c("Number of Cluster (G)", "Number of Observations per Cluster (R)",
                      "Cost Ratio (c1/c2)", "Beta Estimate", "Beta Variance", "Beta Bias", "MSE", "Coverage"),
        booktabs = TRUE, caption = "Metrics Summary Varying Number of Clusters") %>%
  kable_styling(font_size = 7, latex_options = c("repeat_header", "HOLD_position", "scale_down"))

varyGR_summary %>%
  filter(G == 20) %>%
  kable(col.names = c("Number of Cluster (G)", "Number of Observations per Cluster (R)",
                      "Cost Ratio (c1/c2)", "Beta Estimate", "Beta Variance", "Beta Bias", "MSE", "Coverage"),
        booktabs = TRUE, caption = "Metrics Summary Varying Cost Ratio") %>%
  kable_styling(font_size = 7, latex_options = c("repeat_header", "HOLD_position", "scale_down"))
```

```{r, out.width = "80%"}
# plot of G vs. beta variance
ggplot(summary_metrics_df, aes(x = G, y = beta_variance, color = as.factor(c1c2_ratio))) +
  geom_point(size = 2) +
  geom_line(size = 0.5, linetype = "dashed") +
  labs(title = "Beta Variance by Number of Clusters (G)", 
       x = "Number of Clusters (G)", 
       y = "Beta Variance",
       color = "Cost Ratio (c1/c2)") +
  theme_minimal() +
  theme(axis.title = element_text(size = 6),
        title = element_text(size = 6),
        axis.text = element_text(size = 6),
        legend.title = element_text(size = 5),
        legend.text = element_text(size = 5),
        legend.key.size = unit(0.3, "cm"),
        strip.text = element_text(size = 6))

# plot of R vs. beta variance 
ggplot(summary_metrics_df) +
  facet_wrap(~ G) + 
  geom_point(aes(x = R, y = beta_variance, color = as.factor(c1c2_ratio)), size = 2) +
  geom_line(aes(x = R, y = beta_variance), size = 0.5, linetype = "dashed") + 
  labs(title = "Beta Variance by R for Different G", 
       x = "Number of Individuals per Cluster (R)", 
       y = "Beta Variance",
       color = "Cost Ratio (c1/c2)") +
  theme_minimal() +
  theme(axis.title = element_text(size = 6),
        title = element_text(size = 6),
        axis.text = element_text(size = 6),
        legend.title = element_text(size = 5),
        legend.text = element_text(size = 5),
        legend.key.size = unit(0.3, "cm"),
        strip.text = element_text(size = 6),
        legend.position = "bottom")

```
## Vary gamma_sq
```{r}
alpha <- 0
beta <- 1.5
sigma_sq <- 1
B <- 10000
G <- 30
R <- 79
niter <- 100
c1 <- 20
c1c2_ratio <- 5

gamma_sq_list <- seq(0.5, 3, by = 0.5)
summary_metrics_df_gamma <- data.frame()
for (gamma_sq in gamma_sq_list) {
  result_df <- simulate_data_normal(G, alpha, beta, gamma_sq, sigma_sq, c1, c1c2_ratio, B, niter,
                                    folder = data_folder_normal, 
                                    filename = paste0("Normal", "_", G, "_", ratio, "_", alpha, 
                                                      "_", beta, "_", gamma_sq, "_", sigma_sq,
                                                      "_data.csv"))
  c2 <- c1 / c1c2_ratio
  cost_per_cluster <- B/G
  n_c2 <- floor((cost_per_cluster - c1)/c2)
  R <- n_c2 + 1
  data_path <- paste0(data_folder_normal, "Normal", "_", G, "_", ratio, "_", 
                      alpha, "_", beta, "_", gamma_sq, "_", sigma_sq, "_data.csv")
  summary_metrics <- normal_model(data_path, beta, niter, results_folder = results_folder_normal,
                                  filename = paste0("Results_normal", "_", G, "_", ratio, "_",
                                                    alpha, "_", beta, "_", gamma_sq, "_", sigma_sq, ".csv"))
  summary_metrics_df_gamma <- rbind(summary_metrics_df_gamma, summary_metrics)
}

summary_metrics_df_gamma <- summary_metrics_df_gamma %>%
  dplyr::select(-c(G, R, c1, c2, c1c2_ratio, total_cost))

summary_metrics_df_gamma %>%
  kable(col.names = c("Baseline Mean", "Treatment Effect", "Between-cluster Variance", 
                      "Within-cluster Variance", "Beta Variance", "Beta Bias", "MSE", "Coverage"), 
        booktabs = TRUE, caption = "Metrics Summary Varying Between-cluster Variance") %>%
  kable_styling(font_size = 7, latex_options = c("repeat_header", "HOLD_position", "scale_down"))
```

## Vary sigma_sq

```{r}
alpha <- 0
beta <- 1.5
gamma_sq <- 1
B <- 10000
G <- 30
R <- 79
niter <- 100
c1 <- 20
c1c2_ratio <- 5


sigma_sq_list <- seq(0.5, 3, by = 0.5)
summary_metrics_df_sigma <- data.frame()
for (sigma_sq in sigma_sq_list) {
  result_df <- simulate_data_normal(G, alpha, beta, gamma_sq, sigma_sq, c1, c1c2_ratio, B, niter,
                                    folder = data_folder_normal, 
                                    filename = paste0("Normal", "_", G, "_", ratio, "_", alpha, 
                                                      "_", beta, "_", gamma_sq, "_", sigma_sq,
                                                      "_data.csv"))
  c2 <- c1 / c1c2_ratio
  cost_per_cluster <- B/G
  n_c2 <- floor((cost_per_cluster - c1)/c2)
  R <- n_c2 + 1
  data_path <- paste0(data_folder_normal, "Normal", "_", G, "_", ratio, "_", 
                      alpha, "_", beta, "_", gamma_sq, "_", sigma_sq, "_data.csv")
  summary_metrics <- normal_model(data_path, beta, niter, results_folder = results_folder_normal,
                                  filename = paste0("Results_normal", "_", G, "_", ratio, "_",
                                                    alpha, "_", beta, "_", gamma_sq, "_", sigma_sq, ".csv"))
  summary_metrics_df_sigma <- rbind(summary_metrics_df_sigma, summary_metrics)
}

summary_metrics_df_sigma <- summary_metrics_df_sigma %>%
  dplyr::select(-c(G, R, c1, c2, c1c2_ratio, total_cost))

summary_metrics_df_sigma %>%
  kable(col.names = c("Baseline Mean", "Treatment Effect", "Between-cluster Variance", 
                      "Within-cluster Variance", "Beta Variance", "Beta Bias", "MSE", "Coverage"), 
        booktabs = TRUE, caption = "Metrics Summary Varying Within-cluster Variance") %>%
  kable_styling(font_size = 7, latex_options = c("repeat_header", "HOLD_position", "scale_down"))
```

## Poisson Distributed Y
```{r}
alpha <- 0
beta <- 1.5
gamma_sq <- 1
sigma_sq <- 1
B <- 10000
niter <- 100
c1 <- 20
c1c2_ratio_list <- c(2, 5, 10, 20)
G_list = c(5, 10, 15, 20, 25, 30)
data_folder_poisson <- "C:/Users/yingx/OneDrive/Desktop/Fall 2024/PHP 2550/Practical-Data-Analysis-Portfolio/Project3/Data_poisson/"
results_folder_poisson <- "C:/Users/yingx/OneDrive/Desktop/Fall 2024/PHP 2550/Practical-Data-Analysis-Portfolio/Project3/Results_poisson/"

summary_metrics_df_poisson <- data.frame()
for (G in G_list) {
  for (ratio in c1c2_ratio_list) {
    result_df <- simulate_data_poisson(G, alpha, beta, gamma_sq, c1, ratio, B, niter,
                                      folder = data_folder_poisson,
                                      filename = paste0("Poisson", "_", G, "_", ratio, "_", alpha, 
                                                      "_", beta, "_", gamma_sq, "_data.csv"))
    
    c2 <- c1 / ratio
    cost_per_cluster <- B/G
    n_c2 <- floor((cost_per_cluster - c1)/c2)
    R <- n_c2 + 1
    data_path <- paste0(data_folder_poisson, "Poisson", "_", G, "_", ratio, "_", 
                        alpha, "_", beta, "_", gamma_sq, "_data.csv")
    summary_metrics <- poisson_model(data_path, beta, niter, results_folder = results_folder_poisson,
                                    filename = paste0("Results_poisson", "_", G, "_", ratio, "_",
                                                      alpha, "_", beta, "_", gamma_sq, ".csv"))
    summary_metrics_df_poisson <- rbind(summary_metrics_df_poisson, summary_metrics)
  }
}

```

# Reference














# Results











# Discussion












\newpage

```{r ref.label = knitr::all_labels()}
#| echo: false
#| eval: false
```

# Reference